### ISSUE TITLE
policy.json No such file or directory

### ISSUE THREAD

**Issue by willbrowningme** [EFForg/starttls-policy-cli#30]
I'm getting an error relating to the policy.json file not being found.

I installed the package using the following command:
```bash
pip3 install starttls-policy-cli
```
Then ran:
```bash
starttls-policy-cli --generate postfix --policy-dir /home/johndoe
```
This is the error message that is returned:
```bash
Traceback (most recent call last):
  File "/home/johndoe/.local/bin/starttls-policy-cli", line 11, in <module>
    sys.exit(main())
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/main.py", line 39, in main
    _perform(parser.parse_args(), parser)
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/main.py", line 34, in _perform
    _generate(arguments)
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/main.py", line 28, in _generate
    config_generator.generate()
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/configure.py", line 51, in generate
    policy_list = self._load_config()
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/configure.py", line 32, in _load_config
    self._policy_config.load()
  File "/home/johndoe/.local/lib/python3.6/site-packages/starttls_policy_cli/policy.py", line 294, in load
    with io.open(self.filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/johndoe/policy.json'
```

I've tried reinstalling and installing from source but get the same message, any idea why this is?

**Comment by sydneyli** [comment]
Hi @willbrowningme,

You'll need to pull the data source, `policy.json`, regularly from `https://dl.eff.org/starttls-everywhere/policy.json`-- we recommend setting a cronjob to update it and run the policy generation tool regularly; here's a [sample cronjob/script](https://github.com/EFForg/starttls-everywhere/tree/master/scripts).

Let us know if you have any more questions!

**Comment by anonaddy** [comment]
@sydneyli Thanks, completely missed that bit on the site!

**Comment by willbrowningme** [comment]
@sydneyli Thanks, completely missed that bit on the site!
